//$file${.::med_a.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: infusion.qm
// File:  ${.::med_a.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::med_a.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "signals.h"
#include "bsp.h"
#include "med_a.h"
#include "gd32vf103_gpio.h"

Q_DEFINE_THIS_FILE

/* 1. Definition av AO-pekaren (som vi fixade innan) */
static MED_A l_med_a;
MED_A * const AO_MED_A = &l_med_a;

/* 2. QM genererar tillståndsmaskinen här */
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${infusion::MED_A} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${infusion::MED_A} .........................................................

//${infusion::MED_A::SM} .....................................................

//${infusion::MED_A::SM::Idle} ...............................................
QState MED_A_Idle(MED_A * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${infusion::MED_A::SM::Idle}
        case Q_ENTRY_SIG: {
            BSP_ledOff(GPIO_PIN_0);
            status_ = Q_HANDLED();
            break;
        }
        //${infusion::MED_A::SM::Idle::SW1_ON}
        case SW1_ON_SIG: {
            status_ = Q_TRAN(&MED_A_Dosing);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${infusion::MED_A::SM::Dosing} .............................................
QState MED_A_Dosing(MED_A * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${infusion::MED_A::SM::Dosing}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->ledTimer);
            status_ = Q_HANDLED();
            break;
        }
        //${infusion::MED_A::SM::Dosing::initial}
        case Q_INIT_SIG: {
            me->cycleCount = 0U;
            QTimeEvt_armX(&me->ledTimer,
                          BSP_TICKS_PER_SEC/2,
                          BSP_TICKS_PER_SEC/2);
            status_ = Q_TRAN(&MED_A_off);
            break;
        }
        //${infusion::MED_A::SM::Dosing::TIMEOUT}
        case TIMEOUT_SIG: {
            me->cycleCount >= 20;
            status_ = Q_TRAN(&MED_A_Idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${infusion::MED_A::SM::Dosing::off} ........................................
QState MED_A_off(MED_A * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${infusion::MED_A::SM::Dosing::off}
        case Q_ENTRY_SIG: {
            BSP_ledOff(GPIO_PIN_0);
            status_ = Q_HANDLED();
            break;
        }
        //${infusion::MED_A::SM::Dosing::off::TIMEOUT}
        case TIMEOUT_SIG: {
            me->cycleCount++;
            status_ = Q_TRAN(&MED_A_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&MED_A_Dosing);
            break;
        }
    }
    return status_;
}

//${infusion::MED_A::SM::Dosing::on} .........................................
QState MED_A_on(MED_A * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${infusion::MED_A::SM::Dosing::on}
        case Q_ENTRY_SIG: {
            BSP_ledOn(GPIO_PIN_0);
            status_ = Q_HANDLED();
            break;
        }
        //${infusion::MED_A::SM::Dosing::on::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&MED_A_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&MED_A_Dosing);
            break;
        }
    }
    return status_;
}
//$enddef${infusion::MED_A} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* 3. KONSTRUKTORN - Det är denna som saknas enligt ditt felmeddelande! */
void MED_A_ctor(MED_A * const me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&MED_A_initial));

    /* Initiera tidshändelsen */
    QTimeEvt_ctorX(&me->ledTimer, &me->super, TIMEOUT_SIG, 0U);

    /* Nollställ räknaren */
    me->cycleCount = 0U;
}
