//$file${.::magager.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: infusion.qm
// File:  ${.::magager.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::magager.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "signals.h"
#include "manager.h"
#include "med_a.h" /* Mastern måste känna till Arbetaren för att posta till den */

/* 1. Generera interna deklarationer */
//$declare${infusion::Manager} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${infusion::Manager} .......................................................
typedef struct {
// protected:
    QActive super;
} Manager;

// protected:
static QState Manager_initial(Manager * const me, void const * const par);
static QState Manager_Magaer(Manager * const me, QEvt const * const e);
static QState Manager_Alarm(Manager * const me, QEvt const * const e);
//$enddecl${infusion::Manager} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* 2. Skapa den globala instansen och pekaren */
static Manager l_manager;
Manager * const AO_Manager = &l_manager;

/* 3. Generera själva tillståndsmaskinen från QM-ritningen */
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${infusion::Manager} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${infusion::Manager} .......................................................

//${infusion::Manager::SM} ...................................................

//${infusion::Manager::SM::Magaer} ...........................................
static QState Manager_Magaer(Manager * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${infusion::Manager::SM::Magaer::SW1_ON_SIG}
        case SW1_ON_SIG_SIG: {
            QACTIVE_POST(AO_MED_A, Q_NEW(QEvt, START_A_SIG), me);
            status_ = Q_TRAN(&Manager_Magaer);
            break;
        }
        //${infusion::Manager::SM::Magaer::ALARM_ON_SIG}
        case ALARM_ON_SIG_SIG: {
            QACTIVE_POST(MED_A, STOP_SIG, 0);
            status_ = Q_TRAN(&Manager_Alarm);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${infusion::Manager::SM::Alarm} ............................................
static QState Manager_Alarm(Manager * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${infusion::Manager::SM::Alarm::ALARM_OFF_SIG}
        case ALARM_OFF_SIG_SIG: {
            status_ = Q_TRAN(&Manager_Magaer);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${infusion::Manager} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* 4. Konstruktor */
void Manager_ctor(Manager * const me) {
    QMActive_ctor(&me->super, Q_STATE_CAST(&Manager_initial));
}
