//$file${/Users/hugoperss~::app.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: InfusionPump.qm
// File:  ${/Users/hugoperss~::app.h}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${/Users/hugoperss~::app.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef APP_H_
#define APP_H_

#include <stdint.h>
#include <stdbool.h>

//$declare${App} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AppSignals} .........................................................
enum AppSignals {
    ALARM_SIG = Q_USER_SIG,
    RESUME_SIG,
    ALARM_TICK_SIG,

    MAX_PUB_SIG,

    START_MED_SIG,
    STOP_MED_SIG,

    TIMEOUT_SIG,
    DOSE_FINISHED_SIG,
    TICK_SIG,

    MAX_SIG
};

//${App::N_MEDS} .............................................................
#define N_MEDS ((uint8_t)3U)

//${App::MedEvt} .............................................................
typedef struct {
// protected:
    QEvt super;

// public:
    uint8_t medId;
} MedEvt;

// public:
static inline MedEvt * MedEvt_init(MedEvt * const me,
    uint8_t id)
{
    if (me != (MedEvt *)0) {
        me->medId = id;
    }
    return me;
}

//${App::AO_Medicine[N_MEDS]} ................................................
extern QActive * const AO_Medicine[N_MEDS];

//${App::Medicine_ctor} ......................................................
void Medicine_ctor(uint_fast8_t const id);

//${App::AO_PumpMgr} .........................................................
extern QActive * const AO_PumpMgr;

//${App::PumpMgr_ctor} .......................................................
void PumpMgr_ctor(void);
//$enddecl${App} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Medicine} ...........................................................
typedef struct {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;
    uint8_t id;
    uint32_t interval;
    QTimeEvt doseTimer;
    uint32_t ticksLeft;
} Medicine;

// protected:
QState Medicine_initial(Medicine * const me, void const * const par);
QState Medicine_operational(Medicine * const me, QEvt const * const e);
QState Medicine_dosing(Medicine * const me, QEvt const * const e);
QState Medicine_off(Medicine * const me, QEvt const * const e);
QState Medicine_alarm(Medicine * const me, QEvt const * const e);

//${AOs::PumpMgr} ............................................................
typedef struct {
// protected:
    QActive super;

// public:
    bool isAlarmed;

// private:
    QTimeEvt timeEvt;

// public:
    bool medWasRunning[N_MEDS];
} PumpMgr;

// protected:
QState PumpMgr_initial(PumpMgr * const me, void const * const par);
QState PumpMgr_active(PumpMgr * const me, QEvt const * const e);
QState PumpMgr_operational(PumpMgr * const me, QEvt const * const e);
QState PumpMgr_alarm_state(PumpMgr * const me, QEvt const * const e);
//$enddecl${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // APP_H_
