//$file${/Users/hugoperss~::medicine.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: InfusionPump.qm
// File:  ${/Users/hugoperss~::medicine.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${/Users/hugoperss~::medicine.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "app.h"

static Medicine Medicine_inst[N_MEDS];

Q_DEFINE_THIS_FILE

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Medicine} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Medicine} ...........................................................

//${AOs::Medicine::SM} .......................................................
QState Medicine_initial(Medicine * const me, void const * const par) {
    //${AOs::Medicine::SM::initial}
    (void)par;

    QActive_subscribe(Q_ACTIVE_UPCAST(me), ALARM_SIG);
    QActive_subscribe(Q_ACTIVE_UPCAST(me), RESUME_SIG);
    return Q_TRAN(&Medicine_off);
}

//${AOs::Medicine::SM::operational} ..........................................
QState Medicine_operational(Medicine * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Medicine::SM::operational::ALARM}
        case ALARM_SIG: {
            status_ = Q_TRAN(&Medicine_alarm);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Medicine::SM::operational::dosing} ..................................
QState Medicine_dosing(Medicine * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Medicine::SM::operational::dosing}
        case Q_ENTRY_SIG: {
            BSP_ledOn(me->id);
            QTimeEvt_armX(&me->timeEvt, me->interval, me->interval);

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Medicine::SM::operational::dosing}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Medicine::SM::operational::dosing::TIMEOUT}
        case TIMEOUT_SIG: {
            BSP_ledToggle(me->id);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Medicine::SM::operational::dosing::STOP_MED}
        case STOP_MED_SIG: {
            status_ = Q_TRAN(&Medicine_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&Medicine_operational);
            break;
        }
    }
    return status_;
}

//${AOs::Medicine::SM::operational::off} .....................................
QState Medicine_off(Medicine * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Medicine::SM::operational::off}
        case Q_ENTRY_SIG: {
            BSP_ledOff(me->id);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Medicine::SM::operational::off::START_MED}
        case START_MED_SIG: {
            status_ = Q_TRAN(&Medicine_dosing);
            break;
        }
        default: {
            status_ = Q_SUPER(&Medicine_operational);
            break;
        }
    }
    return status_;
}

//${AOs::Medicine::SM::alarm} ................................................
QState Medicine_alarm(Medicine * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Medicine::SM::alarm}
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->timeEvt, 10U, 10U);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Medicine::SM::alarm}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Medicine::SM::alarm::RESUME}
        case RESUME_SIG: {
            status_ = Q_TRAN(&Medicine_off);
            break;
        }
        //${AOs::Medicine::SM::alarm::TIMEOUT}
        case TIMEOUT_SIG: {
            BSP_ledToggle(me->id);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Medicine} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${App::AO_Medicine[N_MEDS]} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_Medicine[N_MEDS]} ................................................
QActive * const AO_Medicine[N_MEDS] ={
    /*Ger möjlighet att referera AO_Medicine[X] när vi vill skcika komandon till en specifik medicin*/
    Q_ACTIVE_UPCAST(&Medicine_inst[0]),
    Q_ACTIVE_UPCAST(&Medicine_inst[1]),
    Q_ACTIVE_UPCAST(&Medicine_inst[2])
};
//$enddef${App::AO_Medicine[N_MEDS]} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${App::Medicine_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::Medicine_ctor} ......................................................
void Medicine_ctor(uint_fast8_t const id) {
    Medicine * const me = &Medicine_inst[id];                                //Medicine * const me: Hämtar en specifik medicin-instats ur den array vi skapat.
    QActive_ctor(&me->super, Q_STATE_CAST(&Medicine_initial));               //QActive_ctor: Berättar för QP att det är ett Active Object och pekar ut vilket tillstånd den ska börja i (initial)
    QTimeEvt_ctorX(&me->timeEvt, Q_ACTIVE_UPCAST(me), TIMEOUT_SIG, 0U);      //QTimeEvt_ctorX: Kopplar ihop medicinens timer (timeEvt) med signalen TIMEOUT_SIG. Det är denna timer som kommer styra hur snabbt LED-lampan blinkar.
    me->id = (uint8_t)id;                                                    //me->id = id: Sparar ID:t (0, 1 eller 2). Detta används för att veta om LED B0, B1 eller B2 ska tändas.

    if (id == 0) {
        me->interval = BSP_TICKS_PER_SEC/4;
    } else if (id == 1) {
        me->interval = BSP_TICKS_PER_SEC/2;
    } else {
        me->interval = BSP_TICKS_PER_SEC;
    }
}
//$enddef${App::Medicine_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
