//$file${/Users/hugoperss~::pumpMgr.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: InfusionPump.qm
// File:  ${/Users/hugoperss~::pumpMgr.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${/Users/hugoperss~::pumpMgr.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h"
#include "app.h"

static PumpMgr PumpMgr_inst;

Q_DEFINE_THIS_FILE

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::PumpMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::PumpMgr} ............................................................

//${AOs::PumpMgr::SM} ........................................................
QState PumpMgr_initial(PumpMgr * const me, void const * const par) {
    //${AOs::PumpMgr::SM::initial}
    (void)par;
    return Q_TRAN(&PumpMgr_operational);
}

//${AOs::PumpMgr::SM::active} ................................................
QState PumpMgr_active(PumpMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::PumpMgr::SM::active::STOP_MED}
        case STOP_MED_SIG: {
            MedEvt const *pe = (MedEvt const *)e;
            me->medWasRunning[pe->medId] = false;
            /* Skapa en NY händelse att skicka vidare */
            MedEvt *newEvt = Q_NEW(MedEvt, STOP_MED_SIG);
            newEvt->medId = pe->medId;
            QACTIVE_POST(AO_Medicine[pe->medId], (QEvt *)newEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::PumpMgr::SM::active::DOSE_FINISHED}
        case DOSE_FINISHED_SIG: {
            MedEvt const *pe = (MedEvt const *)e;
            me->medWasRunning[pe->medId] = false;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::PumpMgr::SM::active::operational} ...................................
QState PumpMgr_operational(PumpMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::PumpMgr::SM::active::operational::START_MED}
        case START_MED_SIG: {
            MedEvt const *pe = (MedEvt const *)e;
            me->medWasRunning[pe->medId] = true;
            /* Skapa en NY händelse för att undvika minneskorruption */
            MedEvt *newEvt = Q_NEW(MedEvt, START_MED_SIG);
            newEvt->medId = pe->medId;

            /* Skicka kopian till det specifika medicin-objektet */
            QACTIVE_POST(AO_Medicine[pe->medId], (QEvt *)newEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::PumpMgr::SM::active::operational::ALARM}
        case ALARM_SIG: {
            QF_PUBLISH(Q_NEW(QEvt, ALARM_SIG), me);
            status_ = Q_TRAN(&PumpMgr_alarm_state);
            break;
        }
        default: {
            status_ = Q_SUPER(&PumpMgr_active);
            break;
        }
    }
    return status_;
}

//${AOs::PumpMgr::SM::active::alarm_state} ...................................
QState PumpMgr_alarm_state(PumpMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::PumpMgr::SM::active::alarm_state}
        case Q_ENTRY_SIG: {
            QF_PUBLISH(Q_NEW(QEvt, ALARM_TICK_SIG), me);

            /*För att alarmet ska starta direkt och inte vänta i 0.1 sekunder*/
            QF_PUBLISH(Q_NEW(QEvt, ALARM_TICK_SIG), me);
            uint8_t i;
            for (i = 0U; i < N_MEDS; ++i) {
                if (me->medWasRunning[i]) { // Bara de som kördes innan larmet!
                    MedEvt *tickEvt = Q_NEW(MedEvt, ALARM_TICK_SIG);
                    tickEvt->medId = i;
                    QACTIVE_POST(AO_Medicine[i], (QEvt *)tickEvt, me);
                }
            }

            QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC/15, BSP_TICKS_PER_SEC/15);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::PumpMgr::SM::active::alarm_state}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::PumpMgr::SM::active::alarm_state::RESUME}
        case RESUME_SIG: {
            QF_PUBLISH(Q_NEW(QEvt, RESUME_SIG), me);
            uint8_t i;
            for (i = 0U; i < N_MEDS; ++i) {
                if (me->medWasRunning[i]) {
                    MedEvt *newEvt = Q_NEW(MedEvt, START_MED_SIG);
                    newEvt->medId = i;
                    QACTIVE_POST(AO_Medicine[i], (QEvt *)newEvt, me);
                }
            }
            status_ = Q_TRAN(&PumpMgr_operational);
            break;
        }
        //${AOs::PumpMgr::SM::active::alarm_state::TIMEOUT}
        case TIMEOUT_SIG: {
            //QF_PUBLISH(Q_NEW(QEvt, ALARM_TICK_SIG), me);
            uint8_t i;
            for (i = 0U; i < N_MEDS; ++i) {
                if (me->medWasRunning[i]) { // Bara de som kördes innan larmet!
                    MedEvt *tickEvt = Q_NEW(MedEvt, ALARM_TICK_SIG);
                    tickEvt->medId = i;
                    QACTIVE_POST(AO_Medicine[i], (QEvt *)tickEvt, me);
                }
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&PumpMgr_active);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::PumpMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::PumpMgr_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::PumpMgr_ctor} .......................................................
void PumpMgr_ctor(void) {
    PumpMgr * const me = &PumpMgr_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&PumpMgr_initial));
    QTimeEvt_ctorX(&me->timeEvt, (QActive *)me, TIMEOUT_SIG, 0U);
    me->isAlarmed = false;
}
//$enddef${App::PumpMgr_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${App::AO_PumpMgr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${App::AO_PumpMgr} .........................................................
QActive * const AO_PumpMgr = Q_ACTIVE_UPCAST(&PumpMgr_inst);
//$enddef${App::AO_PumpMgr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
